apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  template:
    spec:
      containers:
      - name: hello
        image: busybox:1.28
        command:
        - /bin/sh
        - -c
        - date; echo Hello
      restartPolicy: OnFailure
